# Base configuration
base_url = "https://alexkutsan.github.io"
title = "Alexander Kutsan"
description = "Software engeneer"
compile_sass = true
default_language = "en"
theme = "zola-inky"
output_dir = "public"
build_search_index = true
generate_feed = true
feed_filename = "atom.xml"

# Taxonomies - must be defined at the top level
taxonomies = [
    {name = "tags", feed = true, lang = "en"},
    {name = "tags", feed = true, lang = "ru"}
]

[markdown]
highlight_code = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

# Multilingual configuration
[languages]

[languages.en]

[languages.ru]
title = "Александр Куцан"
description = "Программист"

[extra]
avatar = "/avatar.jpg"
image_resizing_disabled = false
image_format = "auto"
image_quality = 80
images_default_size = 512
images_sizes = [64, 512, 1024, 2048]

keywords = "zola, theme, ink, hugo-ink"

link_github_username = "alexkutsan"

menu_links = [
    { url = "/", name = "About" },
    { url = "/en/posts/", name = "Posts" },
    { url = "/tags/", name = "Tags" },
    { url = "https://photo.alexkutsan.me/", name = "Photos" },
    { url = "/search/", name = "Search" },
]

[languages.ru.extra]
menu_links = [
    { url = "/", name = "О блоге" },
    { url = "/ru/posts/", name = "Записи" },
    { url = "/tags/", name = "Теги" },
    { url = "https://photo.alexkutsan.me/", name = "Фото" },
    { url = "/ru/search/", name = "Поиск" },
]

