base_url = "https://alexkutsan.github.io"

title = "Alexander Kutsan"
description = "A simple of a programmer"

default_language = "en"

theme = "DeepThought"

output_dir = "public"
compile_sass = true
minify_html = false
ignored_content = []
generate_feed = true
feed_filename = "rss.xml"

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
# feed_limit = 20

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
hard_link_static = false
build_search_index = true

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]



[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "one-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false


[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = true
include_content = true

[extra]
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
    { code = "en", nav_items = [
        { url = "/", name = "Home" },
        { url = "/posts", name = "Posts" },
        { url = "/tags", name = "Tags" },
        { url = "/categories", name = "Categories" },
    ] },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Alexander Kutsan"
avatar = "avatar.jpg"

[extra.social]
github = "alexkutsan"
linkedin = "alexkutsan"
email = "alexkutsan@gmail.com"


